---
title: "Introduction to SC19051"
author: "Sirui Lin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SC19051}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

__SC19051__ is a simple R package developed to implement the constrained Newton method(_CNM.R_) and compare it to the EM algorithm(_EM.R_).

## Introduction to Gaussian Mixture Model(GMM)

The density of a Gaussian mixture model is of the form:
$f(x ; G)=\int_{\Omega} f(x ; \theta) \mathrm{d} G(\theta)$

where $f(x ; \theta)$ is the kernel density and $G(\theta)$ is the mixing distribution.   

Given a random sample x1,...,xn from density above, the log-likelihood of G has the form:
$l(G)=\sum_{i=1}^{n} \log \left\{\int_{\Omega} f\left(x_{i} ; \theta\right) \mathrm{d} G(\theta)\right\}$

The NPMLE $\hat{G}$ maximizes $l(G)$ is known to be discrete and then has the form: $G(\theta)=\sum_{j=1}^{m} \pi_{j} \delta_{\theta_{j}}$, where $m \leq n$.   

The directional derivative from $G$ to $\delta_{\theta}$, also known as gradient function is deﬁned as:  

$\left.d(\theta ; G) = \frac{\partial l\{(1-\varepsilon) G+\varepsilon \delta_\theta\}}{\partial \varepsilon}\right|_{\varepsilon=0}$

and we have:

$\hat{G} \text { maximizes } l(G) \Leftrightarrow \hat{G} \text { minimizes } \sup _{\theta}\{d(\theta ; G)\} \Leftrightarrow \sup _{\theta}\{d(\theta ; \hat{G})\}=0$

---

## Introduction to Constrained Newton Method

one can refer to [Wang, 2007] for the details of the method.

---
